print("Hola Mundo")
print("Ingrese un numero")
num1 = int(input())
print("ingrese segundo numero")
num2 = int(input())
suma = num1 + num2
num1 = str(num1)
num2 = str(num2)
print("la suma de",num1,"y",num2,"es",suma)
print(num1 + num2)